### ISSUE TITLE
Compiling error on MBP X86

### ISSUE THREAD

**Issue by Jerry-Ge** [usc-cs356/assembly-dojo#1]
Hey Marco, 

I am Jerry from one of your CS356 discussion sessions some time ago. :D How you doing? 

I found this assembly-dojo you created and think this is pretty interesting. 

I clone the code and tried it on my x64 MBP, then, run `make test` it shows me the following errors, do you know why?

![Screen Shot 2021-04-01 at 1 29 48 PM](https://user-images.githubusercontent.com/24451859/113247821-5623f180-92ee-11eb-973e-17c98574bef3.png)

Jerry

**Comment by Jerry-Ge** [comment]
> Hey Marco,
> 
> I am Jerry from one of your CS356 discussion sessions some time ago. :D How you doing?
> 
> I found this assembly-dojo you created and think this is pretty interesting.
> 
> I clone the code and tried it on my x64 MBP, then, run `make test` it shows me the following errors, do you know why?
> 
> ![Screen Shot 2021-04-01 at 1 29 48 PM](https://user-images.githubusercontent.com/24451859/113247821-5623f180-92ee-11eb-973e-17c98574bef3.png)
> 
> Jerry

@paolieri

**Comment by paolieri** [comment]
Are you running inside the class VM?

**Comment by Jerry-Ge** [comment]
Nope...Just run on an Intel-based Mac Book Pro Mac OS

Does this only works on Ubuntu VMs?

**Comment by paolieri** [comment]
Yes, it runs A64 and x64 binaries on a Linux VM using qemu.
Link to the VM is here: https://usc-cs356.github.io/assignments/hellolab.html

**Comment by Jerry-Ge** [comment]
Cool! I will try that. Thanks Marco




________________________________
